/* tslint:disable */
/* eslint-disable */

/**
 * An opaque, clone-able handle to the `renderer::Renderer` instance owned by
 * a [`WgpuRenderer`].
 *
 * Exported to JavaScript so that the game loop can hand it to
 * [`WasmEmulator::attach_gx_renderer`], which allows the GX FIFO parser to
 * dispatch draw actions directly to the GPU renderer as the emulator runs.
 *
 * ```js
 * const wgpuRenderer = await init_webgpu_renderer("gc-canvas");
 * emu.attach_gx_renderer(wgpuRenderer.gx_renderer_handle());
 * ```
 */
export class GxRendererHandle {
    private constructor();
    free(): void;
    [Symbol.dispose](): void;
}

/**
 * GameCube emulator running entirely in the browser via WebAssembly.
 *
 * Exported to JavaScript via `wasm-bindgen`.  The emulator maintains a
 * [`gekko::Cpu`] register file and a flat RAM array.  Compiled PPC blocks are
 * cached as [`WebAssembly::Module`]s and instantiated on demand with
 * JavaScript hook closures for guest memory access.
 */
export class WasmEmulator {
    free(): void;
    [Symbol.dispose](): void;
    /**
     * Advance the internal CPU cycle counter by `delta` emulated cycles.
     *
     * This mirrors the role of `Lazuli::exec`'s per-block cycle accumulator.
     * JavaScript calls this after every block execution with the block's own
     * cycle count so the counter stays accurate regardless of how many blocks
     * happen to run per animation frame.
     */
    add_cpu_cycles(delta: number): void;
    /**
     * Advance the Audio Interface (AI) sample counter by `cpu_cycles`.
     *
     * Call this from the JavaScript game loop after every executed block,
     * passing the block's CPU cycle count (`blockMeta.cycles`).  Internally
     * the method accumulates cycles across blocks and increments the AI sample
     * counter (`AISCNT`) once per audio sample period (10 125 CPU cycles at
     * 48 kHz; 15 187 at 32 kHz, selected by `AICR.AISFR`).
     *
     * When `AISCNT` crosses `AIIT` (the interrupt threshold), the AI
     * interrupt fires: `PI_INT_AI` is set in `PI_INTSR` and
     * [`maybe_deliver_external_interrupt`] is called immediately.
     *
     * Returns `true` when the AI interrupt fires (informational only —
     * interrupt delivery is handled automatically).
     *
     * Mirrors the native `ai::push_streaming_frame` scheduler event which
     * increments `sample_counter` and calls `pi::check_interrupts` at the
     * audio sample rate.
     */
    advance_ai(cpu_cycles: number): boolean;
    /**
     * Tick the decrementer down by `delta` ticks and deliver a decrementer
     * exception if a new underflow occurred and external interrupts are enabled.
     *
     * The Gekko hardware fires the decrementer interrupt on the **edge** when
     * DEC transitions from non-negative to negative (bit 31 goes from 0 to 1).
     * Subsequent calls while DEC is still negative do **not** re-assert the
     * interrupt — the guest OS handler is responsible for writing a new
     * positive value to DEC via `mtspr DEC` to re-arm the timer.
     *
     * PI external interrupts are intentionally **not** delivered here.
     * JavaScript must call [`maybe_deliver_external_interrupt`] whenever MSR.EE
     * transitions from 0 to 1 (e.g. after `rfi` or `mtmsr`), mirroring the
     * native JIT's `msr_changed` → `schedule_now(pi::check_interrupts)` hook.
     *
     * Call this once per JIT block (not just once per animation frame) so that
     * the decrementer exception fires promptly inside spin-wait loops.
     */
    advance_decrementer(delta: number): void;
    /**
     * Advance the CPU time-base register by `delta` ticks.
     *
     * The GameCube's Gekko time base increments at approximately 40.5 MHz
     * (CPU clock / 12).  Call this once per animation frame so that
     * time-base polling loops (`mftb` / `OSWaitVBlank`) see a monotonically
     * increasing counter and do not spin forever.
     *
     * Suggested value: `675_000` ticks per frame (= 40.5 MHz / 60 fps).
     */
    advance_timebase(delta: number): void;
    /**
     * Assert a Video Interface (VI) vertical-retrace interrupt.
     *
     * Call this **once per animation frame** (~60 Hz) from the JavaScript
     * game loop.  The function advances the vertical counter, fires any
     * enabled VI DisplayInterrupt sources (setting their status bits so the
     * OS handler can identify which source fired), sets the VI bit in
     * `PI_INTSR`, and — if the guest CPU has external interrupts enabled
     * (`MSR.EE = 1`) and the OS has unmasked the VI interrupt in `PI_INTMSK`
     * — delivers an `Exception::Interrupt` (vector `0x00000500`) to the CPU.
     *
     * Additionally fires the PE_FINISH interrupt once per frame.  On real
     * hardware PE_FINISH is generated by the GPU when it finishes processing
     * a draw-done command from the GX FIFO.  Without a full GX pipeline the
     * browser build fires it alongside the VI retrace to unblock games that
     * call `GXWaitForDrawDone()` as a frame-sync primitive.
     */
    assert_vi_interrupt(): void;
    /**
     * Attach a WebGPU renderer so the GX FIFO parser can dispatch draw
     * actions directly to the GPU.
     *
     * Call this once after [`init_webgpu_renderer`] succeeds:
     *
     * ```js
     * const wgpuRenderer = await init_webgpu_renderer("gc-canvas");
     * emu.attach_gx_renderer(wgpuRenderer.gx_renderer_handle());
     * ```
     *
     * The handle shares the same internal `Arc` as the `WgpuRenderer`, so
     * actions enqueued by the emulator are visible to `present_xfb`.
     */
    attach_gx_renderer(handle: GxRendererHandle): void;
    /**
     * Number of distinct blocks that have been JIT-compiled to WASM.
     */
    blocks_compiled(): number;
    /**
     * Number of blocks that have been executed.
     */
    blocks_executed(): number;
    /**
     * Number of blocks currently in the module cache.
     */
    cache_size(): number;
    /**
     * Compile the block at `guest_pc` into the internal [`WasmBlockCache`]
     * and return a JS object with metadata.
     */
    compile_and_cache_block(guest_pc: number): any;
    /**
     * Compile the PowerPC basic block starting at `guest_pc` and return its
     * WASM bytecode as a [`Uint8Array`].
     *
     * This is the key step that mirrors the Play! emulator's dynarec-to-WASM
     * pipeline: raw guest machine code is translated into a self-contained
     * WASM binary module.
     *
     * The returned bytes can be passed directly to `WebAssembly.instantiate()`
     * in JavaScript to obtain a callable block.
     */
    compile_block(guest_pc: number): Uint8Array;
    /**
     * High 32 bits of the total emulated CPU cycle counter.
     */
    cpu_cycles_hi(): number;
    /**
     * Low 32 bits of the total emulated CPU cycle counter.
     */
    cpu_cycles_lo(): number;
    /**
     * Size in bytes of the [`gekko::Cpu`] struct.
     */
    cpu_struct_size(): number;
    /**
     * Deliver a PowerPC exception by raw exception-vector offset.
     *
     * Called by JavaScript after a compiled WASM block's `raise_exception(kind)`
     * hook fires and the block's CPU state has been synced back via
     * [`set_cpu_bytes`].  Maps the numeric `kind` (which matches the
     * [`gekko::Exception`] discriminant, e.g. `0x0C00` for Syscall) to the
     * corresponding exception and calls [`gekko::Cpu::raise_exception`] to
     * update `SRR0`, `SRR1`, `MSR`, and `PC` exactly as real hardware would.
     *
     * Returns `true` if the kind was recognised and the exception was
     * delivered; `false` if the kind is unknown (no CPU state change).
     */
    deliver_exception(kind: number): boolean;
    /**
     * Read the Audio Interface Control Register (AICR).
     *
     * JavaScript uses bit 1 (AISFR) to select the audio sample rate
     * (0 = 48 kHz, 1 = 32 kHz) for cycle-accurate AI scheduling and
     * per-frame sample generation.
     */
    get_ai_control(): number;
    /**
     * Return a [`js_sys::Array`] containing the guest PC of every block
     * currently held in the compiled-block cache (module cache).
     */
    get_compiled_block_pcs(): Array<any>;
    /**
     * Serialise the current CPU register state into a [`js_sys::Uint8Array`].
     *
     * The returned bytes match the `#[repr(C)]` in-memory layout of
     * [`gekko::Cpu`].  Write them to offset 0 of the `env.memory` WASM
     * memory before calling `execute(0)` on a compiled block.
     */
    get_cpu_bytes(): Uint8Array;
    /**
     * Current Condition Register (CR) as a raw 32-bit word.
     *
     * The CR is split into eight 4-bit fields CR0–CR7 (CR0 occupies the
     * most-significant nibble, CR7 the least-significant). Each field holds
     * the LT, GT, EQ, and SO comparison flags produced by integer compare
     * instructions or the `Rc` update path.
     */
    get_cr(): number;
    /**
     * Current Counter Register (CTR) value.
     */
    get_ctr(): number;
    /**
     * Return the lower 32-bit word of a Data BAT register.
     *
     * `n` is 0–3 for DBAT0L–DBAT3L.
     */
    get_dbat_l(n: number): number;
    /**
     * Return the upper 32-bit word of a Data BAT register.
     *
     * `n` is 0–3 for DBAT0U–DBAT3U.  These are stored in
     * `cpu.supervisor.memory.dbat[n]` (bits 32–63 of the packed 64-bit
     * `Bat` value, as recorded by `mtspr DBAT0U` etc.).
     *
     * JavaScript reads this alongside [`get_dbat_l`] to implement BAT address
     * translation in the MMIO hook fallback path.
     */
    get_dbat_u(n: number): number;
    /**
     * Current Decrementer (DEC) value (signed; goes negative when it expires).
     */
    get_dec(): number;
    /**
     * Get the primary (ps0) value of FPR[i].
     */
    get_fpr(i: number): number;
    /**
     * Get GPR[i].
     */
    get_gpr(i: number): number;
    /**
     * Return the lower 32-bit word of an Instruction BAT register.
     *
     * `n` is 0–3 for IBAT0L–IBAT3L.
     */
    get_ibat_l(n: number): number;
    /**
     * Return the upper 32-bit word of an Instruction BAT register.
     *
     * `n` is 0–3 for IBAT0U–IBAT3U.
     */
    get_ibat_u(n: number): number;
    /**
     * Current Link Register value.
     */
    get_lr(): number;
    /**
     * Return the raw 512 KiB memory card data for the given slot.
     *
     * - `slot = 0`: EXI channel 0, slot A (standard card port).
     * - `slot = 1`: EXI channel 1, slot B.
     *
     * JavaScript should persist this data in `localStorage` (or OPFS for
     * larger cards) and call [`set_memcard_data`] on startup to restore it.
     */
    get_memcard_data(slot: number): Uint8Array;
    /**
     * Current Machine State Register (MSR) as a raw 32-bit word.
     *
     * Bit 15 (`interrupts` / `EE`) is the external-interrupt enable flag.
     * Check `(msr >> 15) & 1` to see if external interrupts are enabled.
     */
    get_msr(): number;
    /**
     * Get the current GameCube controller button bitmask.
     */
    get_pad_buttons(): number;
    /**
     * Get the current program counter.
     */
    get_pc(): number;
    /**
     * Return a snapshot of the emulator's guest RAM as a [`js_sys::Uint8Array`].
     */
    get_ram_copy(): Uint8Array;
    /**
     * Return the byte offsets of key CPU registers within the [`gekko::Cpu`]
     * struct as a JavaScript object.
     *
     * JavaScript can use these offsets to directly read / write individual
     * registers in the WASM memory buffer that holds the serialised CPU state.
     */
    get_reg_offsets(): any;
    /**
     * Returns the 64-byte SRAM contents as a `Uint8Array`.
     *
     * JavaScript should persist these bytes in `localStorage` and call
     * [`set_sram`] on startup to restore saved settings (language, sound mode,
     * etc.), mirroring the native emulator's on-disk SRAM persistence.
     */
    get_sram(): Uint8Array;
    /**
     * Saved Restore Register 0 (SRR0) — the PC saved when the last exception fired.
     */
    get_srr0(): number;
    /**
     * Saved Restore Register 1 (SRR1) — the MSR saved when the last exception fired.
     */
    get_srr1(): number;
    /**
     * Read a 16-bit value from a GameCube hardware register.
     *
     * Called by the JavaScript `read_u16` hook when the guest address has
     * the prefix `0xCC` or `0xCD`.
     */
    hw_read_u16(addr: number): number;
    /**
     * Read a 32-bit value from a GameCube hardware register.
     *
     * Called by the JavaScript `read_u32` hook when the guest address has
     * the prefix `0xCC` or `0xCD` (GameCube memory-mapped I/O space),
     * **before** the `PHYS_MASK` is applied.  This is necessary because
     * applying `addr & 0x01FFFFFF` to `0xCC006008` yields `0x00006008`,
     * which would silently alias into guest RAM instead of the DVD Interface
     * registers.
     *
     * Both `0xCCxxxxxx` (cached) and `0xCDxxxxxx` (uncached) aliases are
     * normalised to the `0xCC` base before dispatching.
     */
    hw_read_u32(addr: number): number;
    /**
     * Read an 8-bit value from a GameCube hardware register.
     *
     * Most MMIO registers are 16- or 32-bit wide; 8-bit reads are unusual
     * but the OS sometimes uses `lbz` to check single-byte status fields.
     * Returns the appropriate byte from the containing 32-bit register.
     */
    hw_read_u8(addr: number): number;
    /**
     * Write a 16-bit value to a GameCube hardware register.
     *
     * Called by the JavaScript `write_u16` hook when the guest address has
     * the prefix `0xCC` or `0xCD`.
     */
    hw_write_u16(addr: number, val: number): void;
    /**
     * Write a 32-bit value to a GameCube hardware register.
     *
     * Called by the JavaScript `write_u32` hook when the guest address has
     * the prefix `0xCC` or `0xCD`, before `PHYS_MASK` is applied.
     */
    hw_write_u32(addr: number, val: number): void;
    /**
     * Write an 8-bit value to a GameCube hardware register.
     *
     * Reads the containing 32-bit register, merges the byte, and writes back.
     */
    hw_write_u8(addr: number, val: number): void;
    /**
     * Returns the WASM linear-memory pointer to the L2 cache-as-RAM buffer.
     *
     * The L2 cache region is 16 KiB and corresponds to guest addresses
     * `0xE000_0000`–`0xE003_FFFF`.  JavaScript uses this pointer to create a
     * `Uint8Array` view and services reads/writes to those addresses directly,
     * matching the native emulator's `0xE000_0000` L2 cache-RAM region.
     *
     * ```js
     * const l2c = new Uint8Array(wasm_memory().buffer, emu.l2c_ptr(), emu.l2c_size());
     * ```
     */
    l2c_ptr(): number;
    /**
     * Returns the size of the L2 cache-as-RAM buffer in bytes (always 16 KiB).
     */
    l2c_size(): number;
    /**
     * Estimated CPU cycle count of the most recently compiled block.
     *
     * Mirrors [`ppcwasm::WasmBlock::cycles`], which is set to one cycle per
     * PPC instruction (the same heuristic used by ppcjit's `Meta::cycles`).
     * JavaScript should read this immediately after `compile_block` returns
     * and store it per-PC so the game loop can advance the decrementer by
     * the correct number of timebase ticks (`cycles / 12`) rather than a
     * fixed per-block constant.
     */
    last_compiled_cycles(): number;
    /**
     * PPC instruction count of the most recently compiled block.
     */
    last_compiled_ins_count(): number;
    /**
     * Guest PC of the most recently JIT-compiled block (0 if none compiled yet).
     */
    last_compiled_pc(): number;
    /**
     * WASM byte length of the most recently compiled block.
     */
    last_compiled_wasm_bytes(): number;
    /**
     * Disc byte offset of the most recent successful DVD Read (0xA8) DMA.
     *
     * JavaScript reads this after [`take_dma_dirty`] returns `true` to
     * format the `[lazuli] DI: DVD Read` diagnostic line in the apploader-log
     * panel, mirroring the same message logged to the browser console by
     * `process_di_command`.
     */
    last_di_disc_offset(): number;
    /**
     * Physical start address (in emulator RAM) of the most recent successful
     * DVD DMA transfer.
     */
    last_dma_addr(): number;
    /**
     * Byte length of the most recent successful DVD DMA transfer.
     */
    last_dma_len(): number;
    /**
     * Copy `data` into guest RAM starting at `guest_addr`.
     *
     * `guest_addr` may be a GameCube virtual address (`0x8xxxxxxx`) or a raw
     * physical offset; both are handled transparently via the same
     * `0x01FF_FFFF` mask used by [`crate::phys_addr`].
     *
     * Clears the block cache for any PC that overlaps the written region, so
     * that stale compiled blocks are not executed after a ROM reload.
     */
    load_bytes(guest_addr: number, data: Uint8Array): void;
    /**
     * Store a raw GameCube ISO disc image for runtime sector reads.
     *
     * This is the Rust counterpart of Play!'s `DiscImageDevice.ts` +
     * `Js_DiscImageDeviceStream.cpp`: once the ISO bytes are stored here the
     * emulated DVD Interface can service `A8h` (DVD Read) DMA commands during
     * gameplay, so that games that stream textures, audio, or level data from
     * disc continue to work after the initial boot DOL has been loaded.
     *
     * Both raw ISO and CISO (Compact ISO) formats are accepted.  CISO images
     * are detected by the `"CISO"` magic at byte 0 and decompressed to a flat
     * buffer before storage so the runtime DVD-read path can use plain byte
     * slicing without format-awareness.
     *
     * Call this in addition to (not instead of) the DOL-loading path in
     * `parseAndLoadIso` / `load_bytes`.
     */
    load_disc_image(data: Uint8Array): void;
    /**
     * Load an ipl-hle DOL into guest RAM and return its entry point.
     *
     * `data` must contain the raw bytes of a GameCube DOL file built from
     * `crates/ipl-hle/` (via `just ipl-hle build`).  In the browser the
     * caller fetches `ipl-hle.dol` from the same origin and passes the
     * resulting `Uint8Array` here; nothing is embedded in the WASM binary.
     *
     * The DOL header layout (all fields big-endian u32):
     *   0x000  text_offsets[7]   — file offset of each .text section
     *   0x01C  data_offsets[11]  — file offset of each .data section
     *   0x048  text_targets[7]   — guest load address of each .text section
     *   0x064  data_targets[11]  — guest load address of each .data section
     *   0x090  text_sizes[7]     — size in bytes of each .text section
     *   0x0AC  data_sizes[11]    — size in bytes of each .data section
     *   0x0D8  bss_target        — guest address of BSS region
     *   0x0DC  bss_size          — size of BSS region
     *   0x0E0  entry             — entry-point guest address
     *
     * After loading, callers must set `gpr[3]` to the real apploader's entry
     * function address (read from the ISO apploader header at offset `+0x10`)
     * so that ipl-hle's `main(entry)` receives it as its first argument,
     * matching what the native `load_ipl_hle()` does.
     *
     * Returns the ipl-hle entry point (e.g. `0x81300000`).
     */
    load_ipl_hle(data: Uint8Array): number;
    /**
     * Restore the complete emulator state from a savestate byte array.
     *
     * `data` must have been produced by a previous call to [`save_state`].
     * Returns `true` on success, `false` on format mismatch.
     */
    load_state(data: Uint8Array): boolean;
    /**
     * Build the import object descriptor required to instantiate a compiled block.
     *
     * Returns a JavaScript object with metadata that JS can use to wire up its
     * own closures against the emulator's WASM linear memory.
     */
    make_import_descriptor(): any;
    /**
     * Deliver an external interrupt to the CPU if EE=1 and any enabled
     * interrupt is pending in `PI_INTSR & PI_INTMSK`.
     *
     * Call this from JavaScript whenever MSR.EE transitions from 0 to 1
     * (e.g. after `rfi` or `mtmsr` restores EE).  This mirrors the native
     * JIT's `msr_changed` → `schedule_now(pi::check_interrupts)` hook, which
     * only re-checks pending interrupts on an actual MSR-change event — not
     * on every single JIT block.
     *
     * Also called internally whenever a PI_INTSR bit is asserted (VI, DI, SI,
     * …) so the interrupt fires immediately if EE is already enabled.
     */
    maybe_deliver_external_interrupt(): void;
    /**
     * Create a new emulator with `ram_size` bytes of guest RAM.
     *
     * `ram_size` must be a multiple of 65536 (one WASM memory page).
     * For a full GameCube emulation pass `24 * 1024 * 1024` (24 MiB).
     */
    constructor(ram_size: number);
    /**
     * Parse a GameCube disc image (raw ISO or CISO), load the apploader into
     * guest RAM, and store the disc for runtime DVD reads.
     *
     * This method consolidates the disc-loading logic that was previously
     * split between the JavaScript `parseAndLoadIso` function and the
     * [`load_disc_image`] method, moving all format-aware parsing into Rust:
     *
     * 1. **Format detection** — CISO images are decompressed to a flat buffer.
     * 2. **Header validation** — the GameCube magic word (`0xC2339F3D` at
     *    offset `0x1C`) is verified.
     * 3. **Disc header** — the first `0x440` bytes (ISO header + boot info)
     *    are copied to guest RAM at `0x8000_0000`.
     * 4. **Dolphin OS globals** — standard boot-time values are written to
     *    `0x8000_0020`–`0x8000_00FF`, matching what the native IPL ROM writes
     *    before transferring control to the apploader.
     * 5. **Apploader** — the apploader body is loaded at `0x8120_0000`.
     * 6. **Boot DOL** — the header is parsed to read the entry point; sections
     *    are **not** pre-loaded and BSS is **not** zeroed here.  The apploader
     *    (run by ipl-hle) loads every section via DI DMA, making pre-loading
     *    redundant.  Pre-zeroing BSS would also wipe the OS globals written in
     *    step 4 (e.g. arena_lo at `0x8000_0030`) if the game's BSS covers that
     *    region, causing a false "ArenaLo still 0" diagnostic.
     * 7. **Runtime disc** — the flat disc image is stored for later `0xA8`
     *    DVD Read DMA commands.
     *
     * Returns a JavaScript object with the following fields on success:
     *
     * | Field              | Type   | Description                              |
     * |--------------------|--------|------------------------------------------|
     * | `gameName`         | string | Null-terminated game title from the header |
     * | `gameId`           | string | 6-character game identifier               |
     * | `dolEntry`         | number | Boot DOL entry-point address              |
     * | `apploaderEntry`   | number | Apploader entry function address          |
     *
     * Returns a JavaScript `Error` on failure (bad magic, corrupt DOL, …).
     */
    parse_and_load_disc(data: Uint8Array): any;
    /**
     * Total number of `raise_exception` calls since emulator creation.
     */
    raise_exception_count(): number;
    /**
     * Returns a raw pointer (WASM linear memory offset) to the start of the
     * guest RAM buffer.
     *
     * Combine with [`wasm_memory`] and [`ram_size`] to create a live,
     * zero-copy JavaScript view:
     *
     * ```js
     * const ram = new Uint8Array(wasm_memory().buffer, emu.ram_ptr(), emu.ram_size());
     * ```
     */
    ram_ptr(): number;
    /**
     * Returns the size of the guest RAM buffer in bytes.
     */
    ram_size(): number;
    /**
     * Notify the emulator that one compiled block has just been executed.
     */
    record_block_executed(): void;
    /**
     * Increment the `raise_exception` counter.
     */
    record_raise_exception(): void;
    /**
     * Serialize the complete emulator state to a byte array for savestate support.
     *
     * The returned [`js_sys::Uint8Array`] can be saved to `localStorage` or
     * downloaded as a file, then passed back to [`load_state`] to restore.
     *
     * ## Format (little-endian binary)
     *
     * ```text
     *   [4]  magic     = b"LAZU"
     *   [4]  version   = 2
     *   [4]  cpu_size  = size_of::<gekko::Cpu>()
     *   [N]  cpu       = raw bytes of gekko::Cpu
     *   [4]  ram_size  = self.ram.len()
     *   [M]  ram       = self.ram
     *   [4]  pi_intsr
     *   [4]  pi_intmsk
     *   [4]  pad_buttons
     *   [4]  flags     = decrementer_pending as u32
     *   [128] vi_regs  = 32 × u32 (raw VI register file)
     *   [12] si_out    = 3 × u32 SI output buffers 0–2
     *   [4]  si_out3   = SI output buffer 3
     *   [16] si_in_hi  = 4 × u32 SI input buffer high words
     *   [16] si_in_lo  = 4 × u32 SI input buffer low words
     *   [4]  si_poll
     *   [4]  si_comm_ctrl
     *   [4]  si_status
     *   [4]  ai_control
     *   [4]  ai_volume
     *   [4]  ai_sample_count
     *   [4]  ai_interrupt_sample
     * ```
     */
    save_state(): Uint8Array;
    /**
     * Store precise analog axis values for the port-0 controller.
     *
     * Called by the JavaScript input layer once per animation frame after
     * either reading the Gamepad API (full 8-bit resolution) or computing
     * axis values from keyboard `STICK_*` pseudo-buttons (±96 deflection).
     *
     * These values are forwarded verbatim into the SI poll response (bytes 2–7
     * of the 8-byte controller report), replacing the old fixed-deflection
     * calculation that was derived from the digital button bitmask.
     *
     * - `joy_x` / `joy_y`: main stick (0–255, centre = 128; Y: up = larger).
     * - `c_stick_x` / `c_stick_y`: C-Stick (0–255, centre = 128).
     * - `l_trig` / `r_trig`: analog trigger depth (0 = released, 255 = full).
     */
    set_analog_axes(joy_x: number, joy_y: number, c_stick_x: number, c_stick_y: number, l_trig: number, r_trig: number): void;
    /**
     * Restore the CPU register state from raw bytes.
     *
     * `data` must have been produced by a previous call to [`get_cpu_bytes`]
     * and must therefore have length exactly [`cpu_struct_size`] bytes.  Call
     * this after `execute()` returns to sync the register changes made by the
     * compiled block back into the Rust emulator.
     */
    set_cpu_bytes(data: Uint8Array): void;
    /**
     * Set GPR[i].
     */
    set_gpr(i: number, value: number): void;
    /**
     * Overwrite the memory card data for the given slot with `data`.
     *
     * Any number of bytes up to 512 KiB may be written; bytes beyond the
     * internal buffer length are silently ignored.  If `data` is shorter than
     * 512 KiB the remainder of the card stays at its current value (default
     * `0xFF` = erased).
     */
    set_memcard_data(slot: number, data: Uint8Array): void;
    /**
     * Overwrite the Machine State Register with a raw 32-bit value.
     *
     * Call this once after loading a DOL/ISO to establish the CPU state that
     * the IPL ROM would normally leave before handing off to the apploader.
     * The two critical bits are:
     *
     * * **IP** (bit 6, `exception_prefix`) — `0` here so exception vectors
     *   land at `0x000xxxxx` (physical `0x00000900` for the decrementer),
     *   which is within the 24 MiB GameCube RAM.  The default reset value
     *   (`IP = 1`) would put vectors at `0xFFF0xxxx` — beyond RAM.
     * * **EE** (bit 15, `interrupts`) — `1` here so decrementer and external
     *   interrupts can fire.  The real IPL ROM jumps to the apploader with
     *   `EE = 1`; without it, any spin-loop that waits for a decrementer
     *   interrupt would stall forever.
     *
     * Typically called with `0x8000` (`EE = 1`, all other bits cleared).  The
     * game's own `__start` / `OSInit` will reconfigure MSR as needed.
     */
    set_msr(value: number): void;
    /**
     * Set the GameCube controller button bitmask.
     *
     * Called by the JavaScript keyboard handler on every `keydown` / `keyup`
     * event.  The bitmask layout matches the `GC_BTN` constants defined in
     * `bootstrap.js`.
     */
    set_pad_buttons(buttons: number): void;
    /**
     * Set the program counter.
     */
    set_pc(pc: number): void;
    /**
     * Overwrite the 64-byte SRAM with `data`.
     *
     * Call this on emulator startup with bytes previously saved to
     * `localStorage` by [`get_sram`].
     */
    set_sram(data: Uint8Array): void;
    /**
     * Copy `data` back over the emulator's guest RAM.
     */
    sync_ram(data: Uint8Array): void;
    /**
     * Generate up to `n_samples` stereo 16-bit PCM samples from the AI DMA
     * ring buffer and return them as a `Float32Array` of length `n_samples * 2`
     * (interleaved left/right, each sample normalised to `−1.0 … +1.0`).
     *
     * Called once per animation frame by the JavaScript audio pipeline to
     * fill the `SharedArrayBuffer` PCM ring buffer consumed by the
     * `AudioWorkletNode` DSP output worklet.
     *
     * Returns an empty array when the AI DMA is not running (`AudioDmaControl`
     * bit 15 = 0), the DMA buffer length is zero, or `n_samples == 0`.
     */
    take_audio_samples(n_samples: number): Float32Array;
    /**
     * Return `true` if a DVD DMA has written new data into guest RAM since the
     * last call, and reset the flag to `false`.
     */
    take_dma_dirty(): boolean;
    /**
     * Return and clear any EXI UART bytes emitted by the game since the last
     * call.
     *
     * The GameCube OS (`OSReport` → `__OSConsoleWrite`) writes console output
     * via the EXI UART protocol on channel 0 (command `0xA001_0000` then
     * immediate-mode data writes), not via the virtual `0xCC007000` byte port
     * used by ipl-hle.  JavaScript should call this after each emulated block
     * and pipe the returned bytes through the same `stdoutLineBuffer` →
     * `appendApploaderLog` path used for ipl-hle output.
     */
    take_uart_output(): Uint8Array;
    /**
     * Number of compiled blocks that contained at least one unimplemented opcode.
     */
    unimplemented_block_count(): number;
    /**
     * Physical RAM address of the External Frame Buffer as programmed by the
     * game into the VI TFBL register.
     *
     * Returns `0` if the game has not yet configured the VI (e.g. during
     * early boot).  JavaScript falls back to heuristic XFB detection when
     * this returns `0`.
     */
    vi_xfb_addr(): number;
}

/**
 * Opaque handle to the initialised WebGPU rendering context.
 *
 * Exported to JavaScript as `WgpuRenderer`.  When the renderer is
 * unavailable (WebGPU not supported or surface creation failed) the
 * [`init_webgpu_renderer`] factory returns `undefined` instead of this type.
 */
export class WgpuRenderer {
    private constructor();
    free(): void;
    [Symbol.dispose](): void;
    /**
     * Clone and return a [`GxRendererHandle`] backed by this renderer.
     *
     * The handle shares the same internal Arc as this `WgpuRenderer`, so GX
     * actions enqueued through the handle are visible to `present_xfb`.
     */
    gx_renderer_handle(): GxRendererHandle;
    /**
     * Present a 640×480 YUV422 external frame-buffer via the wgpu blitter.
     *
     * `xfb_data` must be a `Uint8Array` (or `ArrayBuffer`-backed view) of
     * exactly `640 × 480 × 2 = 614 400` bytes in GameCube YCbYCr 4:2:2
     * byte order (`[Cb, Y0, Cr, Y1]` per pair of pixels).
     *
     * The function converts the YUV422 data to RGBA8 on the CPU, uploads it
     * to a 640×480 GPU texture, then blits the texture to the swap-chain
     * surface using a fullscreen-quad render pass.
     *
     * Returns `true` on success, `false` if the surface texture is lost or
     * `xfb_data` has the wrong length.
     */
    present_xfb(xfb_data: Uint8Array): boolean;
    /**
     * Reconfigure the swap-chain when the canvas is resized.
     *
     * `width` and `height` are the new canvas dimensions in physical pixels.
     * Must be called from JavaScript whenever the canvas `resize` event fires.
     */
    resize(width: number, height: number): void;
}

/**
 * Returns `true` if the browser exposes `navigator.gpu` (WebGPU is available).
 *
 * WebGPU is the GPU API used by `wgpu` on `wasm32` targets (enabled via the
 * `webgpu` feature).  Call this from JavaScript before attempting to
 * initialise the GPU renderer; fall back to the canvas-based XFB blitter if
 * it returns `false`.
 */
export function check_webgpu_support(): boolean;

/**
 * Initialise a WebGPU rendering surface from a `<canvas>` element.
 *
 * `canvas_id` is the `id` attribute of the canvas element (e.g. `"screen"`).
 *
 * Returns a `Promise<WgpuRenderer | undefined>`:
 * - **`WgpuRenderer`** on success.
 * - **`undefined`** when WebGPU is unavailable, the canvas is not found, or
 *   adapter / device creation fails.
 *
 * Typical call from JS:
 * ```js
 * const renderer = await init_webgpu_renderer("screen");
 * if (renderer) { /* use renderer.present_xfb(rawYuv) each frame */ }
 * ```
 */
export function init_webgpu_renderer(canvas_id: string): Promise<WgpuRenderer | undefined>;

/**
 * Returns the WebAssembly linear memory of this module.
 *
 * JavaScript can use the returned [`WebAssembly::Memory`] together with
 * [`WasmEmulator::ram_ptr`] and [`WasmEmulator::ram_size`] to create a
 * **zero-copy live view** over the emulator's guest RAM:
 *
 * ```js
 * const mem   = wasm_memory();
 * const ptr   = emu.ram_ptr();
 * const size  = emu.ram_size();
 * const ram   = new Uint8Array(mem.buffer, ptr, size);
 * ```
 */
export function wasm_memory(): any;

export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module;

export interface InitOutput {
    readonly memory: WebAssembly.Memory;
    readonly wasmemulator_add_cpu_cycles: (a: number, b: number) => void;
    readonly wasmemulator_advance_decrementer: (a: number, b: number) => void;
    readonly wasmemulator_advance_timebase: (a: number, b: number) => void;
    readonly wasmemulator_blocks_compiled: (a: number) => number;
    readonly wasmemulator_blocks_executed: (a: number) => number;
    readonly wasmemulator_cache_size: (a: number) => number;
    readonly wasmemulator_cpu_cycles_hi: (a: number) => number;
    readonly wasmemulator_cpu_cycles_lo: (a: number) => number;
    readonly wasmemulator_cpu_struct_size: (a: number) => number;
    readonly wasmemulator_deliver_exception: (a: number, b: number) => number;
    readonly wasmemulator_get_ai_control: (a: number) => number;
    readonly wasmemulator_get_compiled_block_pcs: (a: number) => any;
    readonly wasmemulator_get_cpu_bytes: (a: number) => any;
    readonly wasmemulator_get_cr: (a: number) => number;
    readonly wasmemulator_get_ctr: (a: number) => number;
    readonly wasmemulator_get_dbat_l: (a: number, b: number) => number;
    readonly wasmemulator_get_dbat_u: (a: number, b: number) => number;
    readonly wasmemulator_get_dec: (a: number) => number;
    readonly wasmemulator_get_fpr: (a: number, b: number) => number;
    readonly wasmemulator_get_gpr: (a: number, b: number) => number;
    readonly wasmemulator_get_ibat_l: (a: number, b: number) => number;
    readonly wasmemulator_get_ibat_u: (a: number, b: number) => number;
    readonly wasmemulator_get_lr: (a: number) => number;
    readonly wasmemulator_get_memcard_data: (a: number, b: number) => any;
    readonly wasmemulator_get_msr: (a: number) => number;
    readonly wasmemulator_get_pad_buttons: (a: number) => number;
    readonly wasmemulator_get_pc: (a: number) => number;
    readonly wasmemulator_get_ram_copy: (a: number) => any;
    readonly wasmemulator_get_reg_offsets: (a: number) => any;
    readonly wasmemulator_get_sram: (a: number) => any;
    readonly wasmemulator_get_srr0: (a: number) => number;
    readonly wasmemulator_get_srr1: (a: number) => number;
    readonly wasmemulator_l2c_ptr: (a: number) => number;
    readonly wasmemulator_l2c_size: (a: number) => number;
    readonly wasmemulator_last_compiled_cycles: (a: number) => number;
    readonly wasmemulator_last_compiled_ins_count: (a: number) => number;
    readonly wasmemulator_last_compiled_pc: (a: number) => number;
    readonly wasmemulator_last_compiled_wasm_bytes: (a: number) => number;
    readonly wasmemulator_load_state: (a: number, b: number, c: number) => number;
    readonly wasmemulator_raise_exception_count: (a: number) => number;
    readonly wasmemulator_ram_ptr: (a: number) => number;
    readonly wasmemulator_ram_size: (a: number) => number;
    readonly wasmemulator_record_block_executed: (a: number) => void;
    readonly wasmemulator_record_raise_exception: (a: number) => void;
    readonly wasmemulator_save_state: (a: number) => any;
    readonly wasmemulator_set_analog_axes: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
    readonly wasmemulator_set_cpu_bytes: (a: number, b: number, c: number) => void;
    readonly wasmemulator_set_gpr: (a: number, b: number, c: number) => void;
    readonly wasmemulator_set_memcard_data: (a: number, b: number, c: any) => void;
    readonly wasmemulator_set_msr: (a: number, b: number) => void;
    readonly wasmemulator_set_pad_buttons: (a: number, b: number) => void;
    readonly wasmemulator_set_pc: (a: number, b: number) => void;
    readonly wasmemulator_set_sram: (a: number, b: any) => void;
    readonly wasmemulator_sync_ram: (a: number, b: number, c: number) => void;
    readonly wasmemulator_take_audio_samples: (a: number, b: number) => any;
    readonly wasmemulator_unimplemented_block_count: (a: number) => number;
    readonly wasmemulator_load_bytes: (a: number, b: number, c: number, d: number) => void;
    readonly wasmemulator_load_disc_image: (a: number, b: number, c: number) => void;
    readonly wasmemulator_load_ipl_hle: (a: number, b: number, c: number) => number;
    readonly wasmemulator_parse_and_load_disc: (a: number, b: number, c: number) => [number, number, number];
    readonly wasmemulator_compile_and_cache_block: (a: number, b: number) => [number, number, number];
    readonly wasmemulator_compile_block: (a: number, b: number) => [number, number, number];
    readonly wasmemulator_make_import_descriptor: (a: number) => any;
    readonly __wbg_gxrendererhandle_free: (a: number, b: number) => void;
    readonly __wbg_wgpurenderer_free: (a: number, b: number) => void;
    readonly init_webgpu_renderer: (a: number, b: number) => any;
    readonly wgpurenderer_gx_renderer_handle: (a: number) => number;
    readonly wgpurenderer_present_xfb: (a: number, b: number, c: number) => number;
    readonly wgpurenderer_resize: (a: number, b: number, c: number) => void;
    readonly wasmemulator_advance_ai: (a: number, b: number) => number;
    readonly wasmemulator_assert_vi_interrupt: (a: number) => void;
    readonly wasmemulator_hw_read_u16: (a: number, b: number) => number;
    readonly wasmemulator_hw_read_u32: (a: number, b: number) => number;
    readonly wasmemulator_hw_read_u8: (a: number, b: number) => number;
    readonly wasmemulator_hw_write_u16: (a: number, b: number, c: number) => void;
    readonly wasmemulator_hw_write_u32: (a: number, b: number, c: number) => void;
    readonly wasmemulator_hw_write_u8: (a: number, b: number, c: number) => void;
    readonly wasmemulator_last_di_disc_offset: (a: number) => number;
    readonly wasmemulator_last_dma_addr: (a: number) => number;
    readonly wasmemulator_last_dma_len: (a: number) => number;
    readonly wasmemulator_maybe_deliver_external_interrupt: (a: number) => void;
    readonly wasmemulator_take_dma_dirty: (a: number) => number;
    readonly wasmemulator_take_uart_output: (a: number) => [number, number];
    readonly wasmemulator_vi_xfb_addr: (a: number) => number;
    readonly __wbg_wasmemulator_free: (a: number, b: number) => void;
    readonly check_webgpu_support: () => number;
    readonly wasm_memory: () => any;
    readonly wasmemulator_attach_gx_renderer: (a: number, b: number) => void;
    readonly wasmemulator_new: (a: number) => number;
    readonly wasm_bindgen_7a0033f4c224aadb___closure__destroy___dyn_core_1ee01b24a2067afc___ops__function__FnMut__wasm_bindgen_7a0033f4c224aadb___JsValue____Output_______: (a: number, b: number) => void;
    readonly wasm_bindgen_7a0033f4c224aadb___closure__destroy___dyn_core_1ee01b24a2067afc___ops__function__FnMut__wasm_bindgen_7a0033f4c224aadb___JsValue____Output___core_1ee01b24a2067afc___result__Result_____wasm_bindgen_7a0033f4c224aadb___JsError___: (a: number, b: number) => void;
    readonly wasm_bindgen_7a0033f4c224aadb___convert__closures_____invoke___wasm_bindgen_7a0033f4c224aadb___JsValue__core_1ee01b24a2067afc___result__Result_____wasm_bindgen_7a0033f4c224aadb___JsError__: (a: number, b: number, c: any) => [number, number];
    readonly wasm_bindgen_7a0033f4c224aadb___convert__closures_____invoke___js_sys_a2cf80ff77c7437f___Function_fn_wasm_bindgen_7a0033f4c224aadb___JsValue_____wasm_bindgen_7a0033f4c224aadb___sys__Undefined___js_sys_a2cf80ff77c7437f___Function_fn_wasm_bindgen_7a0033f4c224aadb___JsValue_____wasm_bindgen_7a0033f4c224aadb___sys__Undefined______: (a: number, b: number, c: any, d: any) => void;
    readonly wasm_bindgen_7a0033f4c224aadb___convert__closures_____invoke___wasm_bindgen_7a0033f4c224aadb___JsValue_____: (a: number, b: number, c: any) => void;
    readonly wasm_bindgen_7a0033f4c224aadb___convert__closures_____invoke___bool_: (a: number, b: number) => number;
    readonly __wbindgen_malloc: (a: number, b: number) => number;
    readonly __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
    readonly __wbindgen_exn_store: (a: number) => void;
    readonly __externref_table_alloc: () => number;
    readonly __wbindgen_externrefs: WebAssembly.Table;
    readonly __externref_table_dealloc: (a: number) => void;
    readonly __wbindgen_free: (a: number, b: number, c: number) => void;
    readonly __wbindgen_start: () => void;
}

export type SyncInitInput = BufferSource | WebAssembly.Module;

/**
 * Instantiates the given `module`, which can either be bytes or
 * a precompiled `WebAssembly.Module`.
 *
 * @param {{ module: SyncInitInput }} module - Passing `SyncInitInput` directly is deprecated.
 *
 * @returns {InitOutput}
 */
export function initSync(module: { module: SyncInitInput } | SyncInitInput): InitOutput;

/**
 * If `module_or_path` is {RequestInfo} or {URL}, makes a request and
 * for everything else, calls `WebAssembly.instantiate` directly.
 *
 * @param {{ module_or_path: InitInput | Promise<InitInput> }} module_or_path - Passing `InitInput` directly is deprecated.
 *
 * @returns {Promise<InitOutput>}
 */
export default function __wbg_init (module_or_path?: { module_or_path: InitInput | Promise<InitInput> } | InitInput | Promise<InitInput>): Promise<InitOutput>;
